### PR TITLE
Started adding plot echelle in peakbag

### PR DESCRIPTION
**Pull request by grd349**
I'm putting the echelle plot into peakbag.  I'm using the echelle from lighkurve as a base plot and then overplotting the fitted mode frequencies.  It looks good but there are some challenges.

I think there is an issue with the lightkurve echelle which is based around a small problem with the extent keyword in imshow.  The lightkurve team are on it in terms of fixing this.

### CODE REVIEW

**Comment by grd349** [comment]
Screenshot 2019-07-22 at 19 34 24

**Comment by grd349** [comment]
The legend is a bit big.

**Comment by grd349** [comment]
Need to add some docs!

**Comment by ojhall94** [comment]
> The legend is a bit big.

I'd say increase the size of the plot a little as well as decrease the legend a little 👍

**Comment by ojhall94** [comment]
Also, looks sick!!

**Comment by grd349** [comment]
> > The legend is a bit big.
> 
> I'd say increase the size of the plot a little as well as decrease the legend a little 👍

How do I do that in the seismology class?

Is it seismology.plot_echelle(dnu, numax, ..., figsize=[16,9]) ?

@ojhall94

**Comment by ojhall94** [comment]
I thiiink you can do

```python3
fig = plt.figure(figsize=(x, y))
ax = fig.gca()
ax = seismology.plot_echelle(ax)
```

**Comment by nielsenmb** [comment]
I think eventually it should be a generic plot module, so it can be used
for all steps.

So:
1. Raw power
2. Epsilon
3. Asy peakbag results
4. Peakbag results

And with optional ax as input so user can overplot each step.

**Comment by grd349** [comment]
> I thiiink you can do
> 
> ```python
> fig = plt.figure(figsize=(x, y))
> ax = fig.gca()
> ax = seismology.plot_echelle(ax)
> ```

If that was in before then it's possibly been removed ...

    def plot_echelle(self, deltanu=None, numax=None,
                     minimum_frequency=None, maximum_frequency=None,
                     smooth_filter_width=.1,
                     scale='linear', cmap='Blues'):

I'll leave it as subotimal for now so I can move on ...

**Pull request merged**
