### PR TITLE
Issue#199

### PR DESCRIPTION
**Pull request by grd349**
The start to the adding the l=1 odyssey.  I have added a GUI.

Still to do for just the GUI to be useful ... 

- [x] Add some words to the GUI (e.g., label the silders)
- [x] Add [epsilon_g, coupling, d01] slider 
- [x] Add input from star class (either dnu/eps of mode frequencies) 
- [x] Check the numerical consistency of the results (being pragmatic)
- [x] Add an 'output' or 'save' button.
- [ ] Add a 'peakbag_mixed' class that hands everything off to pymc3.
- [ ] Add epsilon changing as a linear function.
- [ ] Add a button to visualise the prior we are getting from reggae.
- [x] Change password to 'Ironman sucks'.

### CODE REVIEW

**Comment by nielsenmb** [comment]
- As I understood it, the gui was just a simple way for us to get a feel for what's going on in the spectrum when we slide different things. So putting in sliders for different variables and expanding the model complexity makes sense. But wouldn't it be a bit overkill to implement too much functionality apart from that? Do we really need the import pbjam and peakbagging parts for example?

- What does numerical consistency mean?

- What part should be modelled hierarchically?

- I prefer 'everything is awesome' as a password.

**Comment by grd349** [comment]
@nielsenmb Good point. 

I was thinking an intermediate implementation would be the sliders to do the current asy_peakbag job but for the l=1.  We could dev all the peakbag l=1 work but based on human intervention.  Then at some point we transition to replacing the sliders (Reggae) with a proper algo.  Make any sense?

**Comment by nielsenmb** [comment]
Yup! That's what I was thinking.

It's a pretty nice teaching tool though, at least I got a much better sense
of what goes on today when we were looking at it. So it's definitely worth
shining it up a bit later.

**Comment by grd349** [comment]
Ironman sucks

**Comment by grd349** [comment]
Screenshot 2019-12-02 at 20 52 52

**Comment by grd349** [comment]
Screenshot 2019-12-02 at 21 06 53

**Comment by grd349** [comment]
I have been looking at epsilon_g for our star of choice (Boeing 4448777).  Is there any theoretical justification for having an epsilon_g that isn't zero.  I'm not talking about about XYZ fitted stuff to models (screw models ;) ) but rather does epsilon_g actually mean anything?  What might epsilon_g vary with in terms of fundamental parameters?

**Comment by grd349** [comment]
OK - we need another meeting to start making a plan.  @nielsenmb should we chat next week?

**Comment by nielsenmb** [comment]
Sure! I'm free any day expect Friday 6th.

**Comment by grd349** [comment]
Reggae is now integrated (not fully but getting there) with the star class and even has an implementation in plotting (plot_echelle).  I want to improve the integration a bit and fix a few of the niggles.  Then once we have docs, comments, tests, and examples in the docs we can think about merging.

If you want to try it on your favourite star (4448777 works best as some numbers are hard coded for now) then just star.run_reggae() after you have run the asy_fit.  You can even call star.reggae.plot_echelle().

**Comment by grd349** [comment]
I also need to add pyqt5 to the requirements.

**Comment by nielsenmb** [comment]
Awesome! So it opens the UI from the star class?

Also having Reggae output a frequency list in some form is useful for some upcoming work if it doesn't already do this.

**Comment by grd349** [comment]
Yes - star.run_reggae() is now a thing!

It outputs some frequencies and then you can star.reggae.plot_echelle()

Screenshot 2020-02-18 at 04 14 43

**Comment by grd349** [comment]
I'm going to close this PR as the cpnest PR has all of this stuff in there and is much more advanced.

**Pull request closed without merging**
