### PR TITLE
Notebook on adding in Yu sample

### PR DESCRIPTION
**Pull request by grd349**
We are going to add in the Yu sample into the PBjam prior.  This PR will manage the process.

The process will proceed in batches starting with stars that are most like those in the prior and slowly expanding outward.

After we have done this we can worry about other samples ... i.e., K2 giants, Serenelli Dwarf/SG Sample, K2 dwarfs, etc.

### CODE REVIEW

**Comment by grd349** [comment]
I'm going to work on the updated bandwidth now ... let's see how it goes!

**Comment by nielsenmb** [comment]
The prior sample does contain some outliers, it might be a good idea to
remove/account for those before updating the bandwidth.

I've been looking at it a bit, and some that stand out

prior.alpha < -0.5 # There are 1-2 fits where alpha is ~1 (log alpha ~ 0)

prior.eps > 0.50 # For some reason there's a fair number of stars with
epsilon < 0.5, this may be due to the way we plot the diagnostic plots,
which allows these to slip through (can explain tomorrow).

There are definitely a few more outliers, they just need to be cut out.

**Comment by grd349** [comment]
OK - gotcha.  Can we look at that tomorrow?

For now I'll add a notebook with the method for estimating the bandwidth.  (btw, with 12000 stars in the prior things are slow!  We should perhaps preselect stars in epsilon given the known inputs).

**Comment by nielsenmb** [comment]
sure, it may also be worth comparing the input to output values. I'm making
a list and checking it twice now.

**Comment by grd349** [comment]
I am happy to merge this if you are @nielsenmb

**Pull request merged**
