### PR TITLE
Added commentary on example advanced 

### PR DESCRIPTION
**Pull request by grd349**
I am working on the commentary of the advanced example.  I'll see where I can get to, and then I'll ask someone to review the commentary.

@nielsenmb I'll also need to check that the .ipynb pulls through into the docs well.  Is there a docs compile command that needs to be run to check this?

@ojhall94 Could you look over the stuff I have written already on lightkurve? 

TODO:

- [x] Explain KDE prior
- [x] Explain asy_peakbag
- [x] Explain peakbag
- [x] Add comparison with literature values.
- [x] Spell check 

Anyone got advice on spell checking markdown?

### CODE REVIEW

**Comment by nielsenmb** [comment]
If you install the latest version of Sphinx you can check if it compiles
locally.

For RTD you need to make sure that the imported packages (numpy, scipy
etc.) are in the requirements.txt file in the PBjam root directory,
otherwise readthedocs can't find the packages. RTD will automatically build
a new version after you make a commit/merge.

So far the only issue I have had with notebooks is if they are corrupted
(e.g. due to mistakes during conflict resolution), then Sphinx and RTD get
stuck with no error messages when they're building the html. If your ipynb
runs fine locally it should also run fine on RTD.

**Comment by ojhall94** [comment]
I'm just going through, fixing typos, checking stuff, improving minor things.

.ipynb's don't vibe well with merging I think. Ill try and push this fast so theres no conflicts.

**Comment by ojhall94** [comment]
Done, looks good and runs through for me!

**Comment by ojhall94** [comment]
Oops nope, I get an error with pbag.sample:

```python3
TypeError: function() got an unexpected keyword argument 'tolerance'
```
This could be a Theano thing--- I'm running 1.0.4. I don't know if this is an easy fix, should I open a separate issue?

**Comment by grd349** [comment]
> Oops nope, I get an error with pbag.sample:
> 
> ```python
> TypeError: function() got an unexpected keyword argument 'tolerance'
> ```
> 
> This could be a Theano thing--- I'm running 1.0.4. I don't know if this is an easy fix, should I open a separate issue?

I forgot to take that out.  Funny - it ran for me and just ignored it as if a kwarg.  Not sure why yours is different but it can be taken out anyway.  (did you set advi=True?)

**Comment by ojhall94** [comment]
Nope, just ran the example notebook as it appears in the branch. Weird! I'm on Python 3.7.3, could be a Python thing.

**Comment by nielsenmb** [comment]
I got this error too just now.

Only when running example-star though, example-session works fine...

**Comment by grd349** [comment]
Please could you review and do a quick spell check for me :)

**Pull request merged**
