### PR TITLE
Cpnest

### PR DESCRIPTION
**Pull request by grd349**
I have added basic CPnest functionality to the branch cpnest.

@nielsenmb - take a look at the example-advanced if you want to play with it.

I still have to do some stuff:

- [x] Check uncertainties
- [x] Add some docs
- [x] Add some unit tests 
- [x] Sort out all the broken tests

Notes: CPnest is slower than the current emcee implementation but in testing I found it to be better able to cope with multimodality and hence should be better at finding the correct solution rather than getting trapped.

CPnest is a nice piece of code but I've only scratched the surface so far.  We should consider trying to write a custom proposal distribution that copes with the high anti-covariance of epsilon and dnu.

I will try and tie this up to the point that it can be reviewed.  As it stands it is certainly worth leaving in.

### CODE REVIEW

**Comment by grd349** [comment]
I also branched from issue #199 so I'll need to finish that up before merge - rolls eyes.

**Comment by nielsenmb** [comment]
Safe to merge?

**Comment by grd349** [comment]
Not safe to merge!  Still working on it.  Also will need to finish #199 and merge #199 into this before merge to master.

**Comment by grd349** [comment]
This branch now has all the cpnest stuff and the reggae integration.  I'm going to close the issue #199 PR becuase this PR has all the stuff now.  

We shouldn't merge this yet ... but it is pretty close to merge ready.

Things still to do - and I need some help here ... 

- [ ] Docs up to scratch
- [ ] Reggae unit tests (needs some thinking)
- [ ] Add words to the example-reggae notebook and the add to read the docs.

@nielsenmb - could you see if you can run the example-reggae.ipynb in docs?

**Comment by nielsenmb** [comment]
Sure, I'll have a look at it.

**Comment by nielsenmb** [comment]
Looks awesome! Works like a charm. 

Wow it's hard to hit all the mixed l=1,m=0 modes. 

A few minor points: 

- In the ipynb, there are a few places where it says `Checkpoint exception raise`

- Not sure what it is, it seems irrelevant. Just haven't seen it before.

- I'm guessing the `pickle dump` bits are just so you don't have to run through everything many times. Can these be deleted?

- The ylim in the spectrum echelle and the reggae echelle don't match.

- Save message in bottom left doesn't look like it's a formatted string. It gets saved to the correct place though.

**Comment by grd349** [comment]
Morning,

Thanks for looking it over.  It is hard to get it right but it might just be close enough.  When we have something automated I'd like to look at improving the asymptotics with glitches, trends, stuff we draw up in the dirt, ... 

> In the ipynb, there are a few places where it says Checkpoint exception raise

This is caused by the import of CPnest.  Should we find a way to supress it?

> I'm guessing the pickle dump bits are just so you don't have to run through everything many times. Can these be deleted?

Yes - but not just yet.   Leave them while we are still in dev.

> The ylim in the spectrum echelle and the reggae echelle don't match.

I have constant problems with the echelle plot.  Are we still inheriting from lightkurve or do we have our own version?

**Comment by grd349** [comment]
@nielsenmb - I'm starting to think about the automated algo for the mixed modes.  I'll need to divide through by the 'best' model of the l=0, 2 modes from the peakbag results.  I see you have some code in peakbag that plots the results.  Do you think you could repurpose this code to make a new attribute in peakbag that is the residual of the fit?

**Comment by nielsenmb** [comment]
Hmm sure I guess. Just the median model divided out? Is there a way to use
the distribution of models from the peakbag fit?

Regarding the echelle, yes we're still using Lightkurves. Might be nice to
make our own at some point, but for now it's working alright, we just need
to fix the inputs I think.

No need to remove Checkpoint exception raise for now, since it doesn't
appear to be an error message. We can just make it an issue to try to fix
it at some point.

**Comment by nielsenmb** [comment]
I'm headed in to the office to grab my screens, so I'll be offline for a
bit.

**Comment by grd349** [comment]
Got luck at the office :)

> Just the median model divided out? 

Yes - I think that is the best compromise between speed and accuracy.  

> Is there a way to use the distribution of models from the peakbag fit?

Not easily (well, sort of easily but at extra computational expense).  I think as we are still performing mode ID we should keep it simple and then perform a final fit as per the l=0,2 method, but this time with all modes.

**Comment by nielsenmb** [comment]
Added `self.res` and `self.ladder_res` to to the call statement in `peakbag`. `res` is the residual in the shape of the spectrum and `ladder_res`  is in the shape of the laddered spectrum (wasn't sure which one you prefered)

**Comment by grd349** [comment]
thanks @nielsenmb - I'll see if I can look at this again on Thursday :)

**Comment by grd349** [comment]
So - I think this has been since merged into master by Martin.  What do we do with this PR?  @nielsenmb

**Comment by nielsenmb** [comment]
The Reggae stuff hasn't been merged, just the CPnest stuff.

I'd create a new PR and copy over the Reggae stuff, and then close this
one. Less chance of conflicts.

**Comment by grd349** [comment]
Good plan!

G

*Dr Guy R. Davies*
PI - ERC CartographY Project
Senior Lecturer in Astrophysics
School of Physics and Astronomy
The University of Birmingham
Edgbaston
Birmingham  B15 2TT

Tel +44 (0) 121 414 4597
G.R.Davies@bham.ac.uk
grd349@gmail.com
davies@bison.ph.bham.ac.u <davies@bison.ph.bham.ac.uk>k
<davies@bison.ph.bham.ac.uk>

The contents of this e-mail may be privileged and are confidential. It may
not be disclosed, used, or copied in any way by anyone other than the
addressee. If received in error please notify the sender then delete it
from your system. Should you communicate with the sender by e-mail, you
consent to The University of Birmingham monitoring and reading any such
correspondence.

**Pull request closed without merging**
