### PR TITLE
Exclude statsmodels v0.11.0 due to bandwidth bug.

### PR DESCRIPTION
**Pull request by alexlyttle**
I discovered a small bug in statsmodels v0.11.0 [here](https://github.com/statsmodels/statsmodels/issues/6511) which causes a ValueError when specifying `bw_fac` in making the KDE in PBjam.

This PR excludes statsmodels v0.11.0 from `requirements.txt`.

I am fixing the issue in statsmodels so hopefully it will be fixed in the next update.

Let me know if there's anything else which may be useful in this PR.

### CODE REVIEW

**Comment by grd349** [comment]
I'm not sure why we are waiting on a test here - I think it is a problem with either the unit tests or github actions.  Either way @nielsenmb can we merge this (I think you have permissions if you want to do this).  I will look at the tests/actions when I get back.

**Comment by alexlyttle** [comment]
I did wonder about the tests, maybe something went over a time limit.

**Update:**

The bug fix has been merged [here](https://github.com/statsmodels/statsmodels/pull/6515) so I'd expect this to be working with later versions of `statsmodels`.

**Comment by grd349** [comment]
Great work Alex!

We do need to fix these tests though.

**Comment by nielsenmb** [comment]
Yep, this can be merged. I don't have the permissions though.

PR #211 is having the same issue. 

They are both trivial updates to requirements.txt

**Pull request merged**
