### PR TITLE
Setup.py pulls from requirements.txt and pbjam.__version__ works again

### PR DESCRIPTION
**Pull request by alexlyttle**
In response to @nielsenmb's [comment](https://github.com/grd349/PBjam/issues/159#issuecomment-537895781) in Issue #159 I have added a line which reads `requirements.txt` into the `install_requires` argument of `setuptools.setup` within `setup.py`. I have tested this and made sure that it correctly imports the list.

I noticed the module `psutil` as a requirement in `setup.py` before making the change, but it was not in `requirements.txt`. I added it to `requirements.txt`, but if it is no longer needed for PBjam then it should be removed before the merge.

I also noticed why `pbjam.__version__` was not working anymore - the line importing it had been removed from `__init__.py` (presumably by mistake in a previous commit). I have added this line back in and now you can call the version.

Finally, I added `.DS_Store` to `.gitignore` as these files are MacOS-specific.

### CODE REVIEW

**Comment by grd349** [comment]
Excellent - Thanks @alexlyttle.

**Comment by grd349** [comment]
@nielsenmb - do you want to look at this before merging?

**Comment by alexlyttle** [comment]
Cheers @grd349!

**Comment by nielsenmb** [comment]
Sure, can have a look tomorrow.

**Comment by nielsenmb** [comment]
Two changes before merge:

1. We should set the required version of astropy==3.2.1. The latest is astropy==3.2.2 and I'm getting some very weird error messages when trying to install that version. Tried this on a clean conda environment, with and without using the PBjam setup.py

2. psutil can be removed. It was used to check memory usage at various stages, but didn't work on BlueBear so I removed all the calls to it in the code. It can safely be removed from the requirements list.

**Comment by alexlyttle** [comment]
Before I commit the fix from Issue #159 I noticed there could be a potential issue in the code. When comparing session.py with older versions (in jar.py) yesterday, I noticed a change which didn't make sense to me (could be a typo).

Line 393 of session.py, in the function `lc_to_lk()` is
```python
    tinyoffset = 1  # to avoid cases LC median = 0 (lk doesn't like it)
```

which applies an offset to the flux, whereas in older versions this is set to `1e-20`.  Was this intentional?

When manually inputting to session the time series from the light curve of the example star in the docs, I still recover the results achieved when session uses the light curve directly - so this may not be an issue. This could be because `to_periodogram()` deals with offsets, but nonetheless I thought I'd ask whether this could be a potential issue?

**Comment by nielsenmb** [comment]
That was just a crude attempt at getting past the zero-mean timeseries as
input issue. It didn't really work completely as intended.

We might be able to just start using the lightkurve normalization('ppm')
now. Ultimately it shouldn't make much of a difference since to_periodogram
takes care of it as you said.

I think you can just leave it at 1 as it is now.

**Comment by alexlyttle** [comment]
That makes sense, thanks for the info. I will just commit the other changes you suggested, forgot to before pushing!

**Comment by nielsenmb** [comment]
Excellent, thanks!

**Pull request merged**
