### PR TITLE
Adding references- PBjam is now 0.1% TeX

### PR DESCRIPTION
**Pull request by nielsenmb**
You can now get a list of references from session or star using the reference() method.
```
sess = session('catname', ....)
sess.references()
```

The list is updated based on what modules are run. So the star reference list won't show CPnest if you only use EMCEE in asy_peakbag for example, or similarly won't show pymc3 if you don't use the peakbag module.

If new modules are added to PBjam, you can add the references by using the _addRef() method
```
star.references._addRef('JoeSmith2020') 
```

References that are not Python related, e.g., Gaia Collaboration are also shown. 

This should be added where relevant (I haven't really come up with a good system yet). The _addRef method does require access the star class instance though. It might be possible to come up with a better way, so functions/classes that don't really know about the star class instance (helper functions) can still add to the list.

If new references are added, add the relevant BibTeX block to pbjam/data/pbjam_references.bib, just like you would in a LaTeX doc.

### CODE REVIEW

**Comment by grd349** [comment]
Neat! :)

**Comment by nielsenmb** [comment]
This is ready to merge by the way.

**Comment by nielsenmb** [comment]
Looks like there's still some workflow stuff going on. Did you switch something back on?

**Comment by grd349** [comment]
Not me (not in master).  Paging @lmcarboneau :)

**Comment by lmcarboneau** [comment]
> Looks like there's still some workflow stuff going on. Did you switch something back on?  
  

> Not me (not in master). Paging @lmcarboneau :)

Sorry, I keep missing notifications in GitHub... I _think_ it should clear up once it's merged? If you branched this before the switch to Travis then it's possible that's what's triggering the workflow. It's also possible that odd branches hanging around with the workflow implementation instead of the Travis CI are keeping workflows active on the repo as a whole. Maybe there's a setting somewhere for removing it - at the very least the PR is passing in Travis so it should to be safe to merge

**Comment by nielsenmb** [comment]
I think this PR needs to be merged by force.

There still seems to be an issue with Workflow.

**Comment by grd349** [comment]
Done

*Dr Guy R. Davies*
PI - ERC CartographY Project
Senior Lecturer in Astrophysics
School of Physics and Astronomy
The University of Birmingham
Edgbaston
Birmingham  B15 2TT

Tel +44 (0) 121 414 4597
G.R.Davies@bham.ac.uk
grd349@gmail.com
davies@bison.ph.bham.ac.u <davies@bison.ph.bham.ac.uk>k
<davies@bison.ph.bham.ac.uk>

The contents of this e-mail may be privileged and are confidential. It may
not be disclosed, used, or copied in any way by anyone other than the
addressee. If received in error please notify the sender then delete it
from your system. Should you communicate with the sender by e-mail, you
consent to The University of Birmingham monitoring and reading any such
correspondence.

**Pull request merged**
